services:
  - type: web
    name: student-app
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18
      - key: NPM_CONFIG_PRODUCTION
        value: false

      # Ajoute ici d'autres variables comme MONGO_URI, JWT_SECRET, etc.
